#!/bin/bash

# Export and patch cartridge releases, then update existing archives with patched executables
# Also apply small tweaks to make release work completely:
# - rename HTML file to index.html to make it playable directly in browser (esp. on itch.io)
# - (TODO) add '.png' to every occurrence of '.p8' in copy of game source before exporting to PNG
# Make sure to first build full game in release

# Configuration: paths
picoboots_scripts_path="$(dirname "$0")/pico-boots/scripts"
game_scripts_path="$(dirname "$0")"
data_path="$(dirname "$0")/data"
# Linux only
carts_dirpath="$HOME/.lexaloffle/pico-8/carts"

# Configuration: cartridge
version=`cat "$data_path/version.txt"`
export_folder="$carts_dirpath/picosonic/v${version}_release"
cartridge_basename="picosonic_v${version}_release"
rel_png_folder="${cartridge_basename}_png_cartridges"
rel_bin_folder="${cartridge_basename}.bin"
rel_web_folder="${cartridge_basename}_web"

# Cleanup png folder as PICO-8 will prompt before overwriting an existing cartridge with the same name,
# and we cannot reply "y" to prompt in headless script (and png tends to keep old label when overwritten)
# Note that we prefer deleting folder content than folder, to avoid file browser/terminal sometimes
# continuing to show old folder in system bin. Make sure to place blob * outside ""
rm -rf "${export_folder}/${rel_png_folder}/"*
# Cleanup bin folder as a bug in PICO-8 makes it accumulate files in .zip for each export (even homonymous files!)
# and we want to remove any extraneous files too
rm -rf "${export_folder}/${rel_bin_folder}/"*

# Create a variant of each non-data cartridge for PNG export, that reloads .p8.png instead of .p8
adapt_for_png_cmd="python3.6 \"$picoboots_scripts_path/adapt_for_png.py\" "${export_folder}/picosonic_*.p8
echo "> $adapt_for_png_cmd"
bash -c "$adapt_for_png_cmd"

if [[ $? -ne 0 ]]; then
  echo ""
  echo "Adapt for PNG step failed, STOP."
  exit 1
fi

# Export via PICO-8 editor: PNG cartridges, binaries, HTML
pico8 -x "$game_scripts_path/export_game_release.p8"

if [[ $? -ne 0 ]]; then
  echo ""
  echo "Export game release via PICO-8 step failed, STOP."
  exit 1
fi

# Patch the runtime binaries in-place with 4x_token, fast_reload, fast_load (experimental) if available
bin_folder="${export_folder}/${rel_bin_folder}"
patch_bin_cmd="\"$picoboots_scripts_path/patch_pico8_runtime.sh\" --inplace \"$bin_folder\" \"$cartridge_basename\""
echo "> $patch_bin_cmd"
bash -c "$patch_bin_cmd"

if [[ $? -ne 0 ]]; then
  echo ""
  echo "Patch bin step failed, STOP."
  exit 1
fi

# Rename HTML file to index.html for direct play-in-browser
html_filepath="${export_folder}/${rel_web_folder}/${cartridge_basename}.html"
mv "$html_filepath" "${export_folder}/${rel_web_folder}/index.html"

# Patch the HTML export in-place with 4x_token, fast_reload
js_filepath="${export_folder}/${rel_web_folder}/${cartridge_basename}.js"
patch_js_cmd="python3.6 \"$picoboots_scripts_path/patch_pico8_js.py\" \"$js_filepath\" \"$js_filepath\""
echo "> $patch_js_cmd"
bash -c "$patch_js_cmd"

if [[ $? -ne 0 ]]; then
  echo ""
  echo "Patch JS step failed, STOP."
  exit 1
fi

# Archiving
# The archives we create here keep all the files under a folder with the full game name
#  to avoid extracting files "in the wild". They are meant for manual distribution and preservation.
# itch.io creates its own folder from the game name + channel, and count on the distributable structure
#  to be stable across versions so butler can only upload differences. So do not upload those archives
#  to itch.io, as the folder inside contain the version number which will change and prevent efficient
#  diffing. For itch.io, just upload the folder directly, and it will generate the zip.
# The exception is OSX, when the .app folder is at the top of the PICO-8 archive,
#  and we can upload either the .app folder directly or the .zip containing it.
pushd "${export_folder}"

  # PNG cartridges archive (delete existing one to be safe)
  rm -f "${cartridge_basename}_png_cartridges.zip"
  zip -r "${cartridge_basename}_png_cartridges.zip" "$rel_png_folder"

  # HTML archive (delete existing one to be safe)
  rm -f "${cartridge_basename}_web.zip"
  zip -r "${cartridge_basename}_web.zip" "${cartridge_basename}_web"

  # Bin archives
  pushd "${rel_bin_folder}"

    # Linux archive

    # Rename linux folder with full game name so our archive contains a self-explanatory folder ()
    mv "linux" "${cartridge_basename}_linux"

    # To minimize operations, do not recreate the archive, just replace the executable in the archive generated by PICO-8 export
    # with the patched executable. We still get some warnings about "Local Version Needed To Extract does not match CD"
    # on other files, so make the operation quiet (-q)
    zip -q "${cartridge_basename}_linux.zip" "${cartridge_basename}_linux/${cartridge_basename}"


    # OSX archive

    # Replace the executable in the archive generated by PICO-8 export with the patched executable
    zip -q "${cartridge_basename}_osx.zip" "${cartridge_basename}.app/Contents/MacOS/${cartridge_basename}"


    # Windows archive

    # Rename linux folder with full game name so our archive contains a self-explanatory folder as the initial archive
    mv "windows" "${cartridge_basename}_windows"

    # To minimize operations, do not recreate the archive, just replace the executable in the archive generated by PICO-8 export
    # with the patched executable. We still get some warnings about "Local Version Needed To Extract does not match CD"
    # on other files, so make the operation quiet (-q)
    zip -q "${cartridge_basename}_windows.zip" "${cartridge_basename}_windows/${cartridge_basename}.exe"

  popd

popd
