picotest = require("picotest")
math = require("math")

function test_math(desc,it)

  desc('almost_eq', function ()
    it('2.506 ~ 2.515', function ()
      return almost_eq(2.506, 2.515)
    end)
    it('2.505 ~! 2.516', function ()
      return not almost_eq(2.505, 2.516)
    end)
    it('-5.984 ~ -5.9835 with eps=0.001', function ()
      return almost_eq(-5.984, -5.9835, 0.001)
    end)
    it('-5.984 !~ -5.9828 with eps=0.001', function ()
      return not almost_eq(-5.984, -5.9828, 0.001)
    end)
  end)

  desc('tile_vector._init', function ()
    it('should create a new tile vector with the right coordinates', function ()
      local loc = tile_vector(2, -6)
      return loc.i == 2 and loc.j == -6
    end)
  end)

  desc('tile_vector._tostring', function ()
    it('should return a string representation with the right coordinates', function ()
      local tile_vec = tile_vector(2, -6)
      return tile_vec:_tostring() == "tile_vector(2, -6)"
    end)
  end)

  desc('tile_vector.__eq', function ()
    it('should return true if tile vectors have the same coordinates', function ()
      local tile_vec1 = tile_vector(1, -4)
      local tile_vec2 = tile_vector(1, -4)
      return tile_vec1 == tile_vec2
    end)
    it('should return false if tile vectors have different coordinates', function ()
      local tile_vec1 = tile_vector(1, -4)
      local tile_vec2 = tile_vector(1, -5)
      return tile_vec1 ~= tile_vec2
    end)
  end)

  desc('sprite_id_location._tostring', function ()
    it('should return a string representation with the right coordinates', function ()
      local sprite_id_loc = sprite_id_location(2, -6)
      return sprite_id_loc:_tostring() == "sprite_id_location(2, -6)"
    end)
  end)

  desc('sprite_id_location.__eq', function ()
    it('should return true if sprite locations have the same coordinates', function ()
      local tile_vec1 = sprite_id_location(1, -4)
      local tile_vec2 = sprite_id_location(1, -4)
      return tile_vec1 == tile_vec2
    end)
    it('should return false if sprite locations have different coordinates', function ()
      local tile_vec1 = sprite_id_location(1, -4)
      local tile_vec2 = sprite_id_location(1, -5)
      return tile_vec1 ~= tile_vec2
    end)
  end)

  desc('sprite_id_location.to_sprite_id', function ()
    it('(2 2) => 34', function ()
      return sprite_id_location(2, 2):to_sprite_id() == 34
    end)
    it('(15 1) => 31', function ()
      return sprite_id_location(15, 1):to_sprite_id() == 31
    end)
  end)

  desc('location._tostring', function ()
    it('should return a string representation with the right coordinates', function ()
      local loc = location(2, -6)
      return loc:_tostring() == "location(2, -6)"
    end)
  end)

  desc('location.__eq', function ()
    it('should return true if locations have the same coordinates', function ()
      local loc1 = location(1, -4)
      local loc2 = location(1, -4)
      return loc1 == loc2
    end)
    it('should return false if locations have different coordinates', function ()
      local loc1 = location(1, -4)
      local loc2 = location(1, -5)
      return loc1 ~= loc2
    end)
  end)

  desc('location.to_topleft_position', function ()
    it('(1 2) => (8 16)', function ()
      return location(1, 2):to_topleft_position() == vector(8, 16)
    end)
  end)

  desc('location.to_center_position', function ()
    it('(1 2) => (12 20)', function ()
      return location(1, 2):to_center_position() == vector(12, 20)
    end)
  end)

  desc('vector._init', function ()
    it('should create a new vector with the right coordinates', function ()
      local vec = vector(2, -6)
      return vec.x == 2 and vec.y == -6
    end)
  end)

  desc('vector._tostring', function ()
    it('should return a string representation with the right coordinates', function ()
      local vec = vector(2, -6)
      return vec:_tostring() == "vector(2, -6)"
    end)
  end)

  desc('vector.__eq', function ()
    it('should return true if vectors have the same coordinates', function ()
      local vec1 = vector(1, -4)
      local vec2 = vector(1, -4)
      return vec1 == vec2
    end)
    it('should return false if vectors have different coordinates', function ()
      local vec1 = vector(1, -4)
      local vec2 = vector(1, -5)
      return vec1 ~= vec2
    end)
  end)

  desc('vector._almost_eq and vector:almost_eq', function ()
    it('vector(2.50501 5.8) ~ vector(2.515 5.79) (static version)', function ()
      -- due to precision issues, 2.505 !~ 2.515 with default eps=0.01!
      return vector._almost_eq(vector(2.50501, 5.8), vector(2.515, 5.79))
    end)
    it('vector(2.50501 5.8) ~ vector(2.515 5.79)', function ()
      return vector(2.50501, 5.8):almost_eq(vector(2.515, 5.79))
    end)
    it('vector(2.505 5.8) !~ vector(2.515 5.788)', function ()
      return not vector(2.505, 5.8):almost_eq(vector(2.515, 5.788))
    end)
    it('vector(2.505 5.8) ~ vector(2.5049 5.799) with eps=0.001', function ()
      return vector(2.505, 5.8):almost_eq(vector(2.5049, 5.799), 0.001)
    end)
    it('vector(2.505 5.8) !~ vector(2.5047 5.789) with eps=0.001', function ()
      return not vector(2.505, 5.8):almost_eq(vector(2.5047, 5.789), 0.001)
    end)
  end)

  desc('vector.__add', function ()
    it('(3 2) + (5 3) => (8 5)', function ()
      return vector(3, 2) + vector(5, 3) == vector(8, 5)
    end)
  end)

  desc('vector.__sub', function ()
    it('(3 2) - (5 3) => (-2 -1)', function ()
      return vector(3, 2) - vector(5, 3) == vector(-2, -1)
    end)
  end)

  desc('vector.__mul', function ()
    it('(3 2) * -2 => (-6 -4)', function ()
      return vector(3, 2) * -2 == vector(-6, -4)
    end)
    it('4 * (-3 2) => (-12 8)', function ()
      return 4 * vector(-3, 2) == vector(-12, 8)
    end)
    it('(-3 2) * (-12 8) => assert', function ()
      -- this should assert
      -- local _ = vector(-3, 2) * vector(-12, 8)
      -- return false
    end)
  end)

  desc('vector.__div', function ()
    it('(3 2) / -2 => (-6 -4)', function ()
      return vector(3, 2) / -2 == vector(-1.5, -1)
    end)
    it('4 / (-3 2) => assert', function ()
      -- this should assert
      -- local _ = 4 / vector(-3, 2)
      -- return false
    end)
    it('(-3 2) / 0 => assert', function ()
      -- this should assert
      -- local _ = vector(-3, 2) / 0
      -- return false
    end)
  end)

  desc('vector.zero()', function ()
    it('should be vector(0, 0)', function ()
      return vector.zero() == vector(0, 0)
    end)
    it('should be mutable', function ()
      local z = vector.zero()
      z.x = 5
      return z.x == 5
    end)
  end)

  desc('vector.is_zero()', function ()
    it('vector.zero() is zero', function ()
      return vector.zero():is_zero()
    end)
    it('(0 0) is zero', function ()
      return vector(0, 0):is_zero()
    end)
    it('(2 3) is not zero', function ()
      return not vector(2, 3):is_zero()
    end)
  end)

  desc('vector.sqr_magnitude', function ()
    it('(4 3) => 25', function ()
      return vector(4, 3):sqr_magnitude() == 25
    end)
    it('(-4 3) => 25', function ()
      return vector(-4, 3):sqr_magnitude() == 25
    end)
    it('(9 -14.2) => 282.64', function ()
      return almost_eq(vector(9, -14.2):sqr_magnitude(), 282.64)
    end)
    it('(0 0) => 0', function ()
      return vector.zero():sqr_magnitude() == 0
    end)
  end)

  desc('vector.magnitude', function ()
    it('(4 3) => 5', function ()
      return almost_eq(vector(4, 3):magnitude(), 5)
    end)
    it('(-4 3) => 5', function ()
      return almost_eq(vector(-4, 3):magnitude(), 5)
    end)
    it('(9 -14.2) => 16.811900547', function ()
      return almost_eq(vector(9, -14.2):magnitude(), 16.811900547)
    end)
    it('(0 0) => 0', function ()
      return vector.zero():magnitude() == 0
    end)
  end)

  desc('vector.normalized', function ()
    it('(1 -1) => (0.707... -0.707...)', function ()
      return vector(1, -1):normalized():almost_eq(vector(0.707, -0.707))
    end)
    it('(4 3) => (0.8 0.6)', function ()
      return vector(4, 3):normalized():almost_eq(vector(0.8, 0.6))
    end)
    it('(0 0) => (0 0)', function ()
      return vector.zero():normalized():almost_eq(vector.zero())
    end)
  end)

  desc('vector.normalize', function ()
    it('(1 -1) => (0.707... -0.707...) in place', function ()
      local v = vector(1, -1)
      v:normalize()
      return v:almost_eq(vector(0.707, -0.707))
    end)
    it('(4 3) => (0.8 0.6) in place', function ()
      local v = vector(4, 3)
      v:normalize()
      return v:almost_eq(vector(0.8, 0.6))
    end)
    it('(0 0) => (0 0) in place', function ()
      local v = vector(0, 0)
      v:normalize()
      return v == vector(0, 0)
    end)
  end)

  desc('vector.with_clamped_magnitude', function ()
    it('(1 -1).with_clamped_magnitude(1) => (0.707... -0.707...)', function ()
      return vector(1, -1):with_clamped_magnitude(1):almost_eq(vector(0.707, -0.707))
    end)
    it('(4 3).with_clamped_magnitude(10) => (4 3)', function ()
      return vector(4, 3):with_clamped_magnitude(10):almost_eq(vector(4, 3))
    end)
    it('(4 3).with_clamped_magnitude(5) => (4 3)', function ()
      return vector(4, 3):with_clamped_magnitude(5):almost_eq(vector(4, 3))
    end)
    it('(4 3).with_clamped_magnitude(0) => (0 0)', function ()
      return vector(4, 3):with_clamped_magnitude(0):almost_eq(vector(0, 0))
    end)
    it('(0 0).with_clamped_magnitude(5) => (0 0)', function ()
      return vector(0, 0):with_clamped_magnitude(5):almost_eq(vector(0, 0))
    end)
  end)

  desc('vector.clamp_magnitude', function ()
    it('(4 -3).clamp_magnitude(2) => (1.6 -1.2)', function ()
      local v = vector(4, -3)
      v:clamp_magnitude(2)
      return v:almost_eq(vector(1.6, -1.2))
    end)
    it('(4 3).clamp_magnitude(10) => (4 3)', function ()
      local v = vector(4, 3)
      v:clamp_magnitude(10)
      return v:almost_eq(vector(4, 3))
    end)
    it('(4 3).clamp_magnitude(5) => (4 3)', function ()
      local v = vector(4, 3)
      v:clamp_magnitude(5)
      return v:almost_eq(vector(4, 3))
    end)
    it('(4 3).clamp_magnitude(0) => (0 0)', function ()
      local v = vector(4, 3)
      v:clamp_magnitude(0)
      return v:almost_eq(vector(0, 0))
    end)
    it('(0 0).clamp_magnitude(5) => (0 0)', function ()
      local v = vector(0, -0)
      v:clamp_magnitude(5)
      return v:almost_eq(vector(0, 0))
    end)
  end)
  desc('vector.with_clamped_magnitude_cardinal', function ()
    it('(1 -1).with_clamped_magnitude_cardinal(1) => (1 -1)', function ()
      return vector(1, -1):with_clamped_magnitude_cardinal(1):almost_eq(vector(1, -1))
    end)
    it('(4 -3).with_clamped_magnitude_cardinal(2) => (2 -2)', function ()
      return vector(4, -3):with_clamped_magnitude_cardinal(2):almost_eq(vector(2, -2))
    end)
    it('(-4 2).with_clamped_magnitude_cardinal(3) => (-3 3)', function ()
      return vector(-4, 2):with_clamped_magnitude_cardinal(3):almost_eq(vector(-3, 2))
    end)
    it('(4 -8).with_clamped_magnitude_cardinal(3 5) => (3 -5)', function ()
      return vector(4, -8):with_clamped_magnitude_cardinal(3, 5):almost_eq(vector(3, -5))
    end)
    it('(0 0).with_clamped_magnitude_cardinal(5) => (0 0)', function ()
      return vector(0, 0):with_clamped_magnitude_cardinal(5):almost_eq(vector(0, 0))
    end)
  end)

  desc('vector.clamp_magnitude_cardinal', function ()
    it('(4 -3).clamp_magnitude_cardinal(2 6) => (2, -3)', function ()
      local v = vector(4, -3)
      v:clamp_magnitude_cardinal(2, 6)
      return v:almost_eq(vector(2, -3))
    end)
    it('(4 3).clamp_magnitude_cardinal(10) => (4 3)', function ()
      local v = vector(4, 3)
      v:clamp_magnitude_cardinal(10)
      return v:almost_eq(vector(4, 3))
    end)
    it('(-4 3).clamp_magnitude_cardinal(5 1) => (-4 1)', function ()
      local v = vector(-4, 3)
      v:clamp_magnitude_cardinal(5, 1)
      return v:almost_eq(vector(-4, 1))
    end)
    it('(-4 -3).clamp_magnitude_cardinal(2) => (-2 -2)', function ()
      local v = vector(-4, -3)
      v:clamp_magnitude_cardinal(2)
      return v:almost_eq(vector(-2, -2))
    end)
    it('(0 0).clamp_magnitude_cardinal(5) => (0 0)', function ()
      local v = vector(0, 0)
      v:clamp_magnitude_cardinal(5)
      return v:almost_eq(vector(0, 0))
    end)
  end)

end

add(picotest.test_suite, test_math)


-- pico-8 functions must be placed at the end to be parsed by p8tool

function _init()
  picotest.test('math', test_math)
end

-- empty update allows to close test window with ctrl+c
function _update()
end
