require("bustedhelper")
require("game/data/tile_data")
local tile_test_data = require("game/test_data/tile_test_data")

describe('tiledata', function ()

  setup(function ()
    stub(tile_test_data, "setup")
    stub(tile_test_data, "teardown")
    stub(pico8, "clear_map")
  end)

  teardown(function ()
    tile_test_data.setup:revert()
    tile_test_data.teardown:revert()
    pico8.clear_map:revert()
  end)

  after_each(function ()
    tile_test_data.setup:clear()
    tile_test_data.teardown:clear()
    pico8.clear_map:clear()
  end)

  describe('setup_map_data', function ()
    it('should call setup on tile_test_data (busted only)', function ()
      setup_map_data()
      assert.spy(tile_test_data.setup).was_called(1)
      assert.spy(tile_test_data.setup).was_called_with()
    end)
  end)

  describe('teardown_map_data', function ()
    it('should call teardown on tile_test_data (busted only)', function ()
      teardown_map_data()
      assert.spy(tile_test_data.teardown).was_called(1)
      assert.spy(tile_test_data.teardown).was_called_with()
    end)
  end)

  describe('clear_map', function ()
    it('should call clear_map from pico8api (busted only)', function ()
      clear_map()
      assert.spy(pico8.clear_map).was_called(1)
      assert.spy(pico8.clear_map).was_called_with(pico8)
    end)
  end)

end)
